services:
  qdrant-db:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped

  redis-cache:
    image: redis:alpine
    container_name: rag-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rag-web:
    build: 
      context: ./bot
      dockerfile: Dockerfile
    container_name: rag-web
    ports:
      - "8000:8000"
    volumes:               
      - ./Data:/app/Data  
    depends_on:
      - qdrant-db
      - redis-cache
    environment:
      - REDIS_HOST=redis-cache
      - QDRANT_URL=http://qdrant-db:6333
      - Ai_Api_Key=${Ai_Api_Key}
    restart: unless-stopped
